services:
  dictionary-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'dictionary-backend'
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install --legacy-peer-deps && npm run build && npx prisma generate && npx prisma migrate deploy && npm start"
    depends_on:
      - dictionary-backend-database

  dictionary-backend-database:
    image: mysql:8.0
    container_name: dictionary-backend-database
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dbname}
      TZ: 'America/Sao_Paulo'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: local
